const quotes = [
  {photoUrl: 'https://t3.ftcdn.net/jpg/02/56/78/44/360_F_256784442_zsvl2Rey5OvDC9c2PkY5ao5KRxvuD342.jpg', author: 'Goethe J.W.', quote: 'Everything is hard before it is easy'},
  {photoUrl: 'https://t3.ftcdn.net/jpg/01/23/64/30/360_F_123643087_EzxKkWD59QQ5nPdWkEBWt3SdhIayuJiy.jpg', author: 'Martin Eden (Jack London)', quote: 'When playing in an unfamiliar game, never do the first move'},
  {photoUrl: 'https://t4.ftcdn.net/jpg/01/57/20/93/360_F_157209380_xDvVKrDWdN5OlOD0FJdgcBzNnDdCkElY.jpg', author: 'Jerzy Gregorek', quote: 'Easy choices, hard life. Hard choices, easy life'},
  {photoUrl: 'https://www.seekpng.com/png/detail/22-225857_thinker-thinking-clipart.png', author: '', quote: 'Watch your thoughts - they become words. Watch your words - they become actions. Watch your actions - they become habits. Watch your habits - they become a character. Watch your character - it determines your destiny'},
  {photoUrl: 'https://thumbs.dreamstime.com/b/focus-concentrate-27100200.jpg', author: '', quote: 'We attract what we focus on'},
  {photoUrl: 'https://thumbs.dreamstime.com/b/fear-words-built-word-blocks-red-color-top-letter-f-falling-over-little-d-man-who-alarmed-afraid-white-background-29810913.jpg', author: 'Jamie Foxx', quote: 'What is on the other side of fear? Nothing.'},
  {photoUrl: 'https://www.incimages.com/uploaded_files/image/1920x1080/getty_846814862_2000133420009280262_352558.jpg', author: 'Janusz Wisniewski', quote: 'It is better to be self-confident, mistaken than to doubt, being right'},
  {photoUrl: 'https://etimg.etb2bimg.com/photo/93910025.cms', author: 'Lucius Annaeus Seneca', quote: 'We learn not for school but for life'},
  {photoUrl: 'https://media.istockphoto.com/id/1253693005/vector/cute-little-kid-girl-think-with-question-mark.jpg?s=612x612&w=0&k=20&c=lwyQ1mMzWkBI1_CgsbmnUVOxrW2g0irKR0KF5i5MBNw=', author: 'John Powell', quote: 'The only real mistake is the one from which we learn nothing'},
  {photoUrl: 'https://thumbs.dreamstime.com/b/act-concept-d-people-man-person-cubes-37051792.jpg', author: 'Guy Julius Caesar', quote: 'Problems make smart people act and  make dumb people depressed.'},
  {photoUrl: 'https://cdn.ldsliving.com/dims4/default/41cb455/2147483647/strip/true/crop/640x345+0+0/resize/640x345!/format/jpg/quality/90/?url=http%3A%2F%2Flds-living-brightspot.s3.amazonaws.com%2Fad%2F16%2F11341573cb7d3ddd8729c1265fcf%2F37222.jpg', author: 'Seneca', quote: 'We suffer more often in imagination than in reality'},
  {photoUrl: 'https://www.thespruce.com/thmb/6UR-mfoMtdVAnWNlD6rP1qMCiU0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/how-to-create-daily-routine-hero-9abc3e09a46b49fe85b7038f65a5abbc.jpg', author: 'Darren Hardy, The Compound Effect', quote: 'You will never change your life until you change something you do daily. The secret of your success is found in your daily routine.'},
  {photoUrl: 'https://www.oxfordmartin.ox.ac.uk/images/_810x540_crop_center-center_none/AdobeStock_276147368.png', author: 'Darren Hardy, The Compound Effect', quote: 'Don\’t wish it were easier; wish you were better.'},
  {photoUrl: 'https://everydaypower.com/wp-content/uploads/2016/07/7-Reasons-to-Become-a-More-Responsible-Person-.jpg', author: 'Darren Hardy, The Compound Effect', quote: 'You alone are responsible for what you do, don\’t do, or how you respond to what\’s done to you.'},
  {photoUrl: 'https://media.licdn.com/dms/image/C4D12AQETMd6f3VxjNg/article-cover_image-shrink_720_1280/0/1622901713472?e=2147483647&v=beta&t=HPsT_m58GdQYLg_ZSPJg-NIDXg1KetesdTP4DaPyWcI', author: 'Darren Hardy, The Compound Effect', quote: 'Small, Smart Choices + Consistency + Time = RADICAL DIFFERENCE'},
  {photoUrl: 'https://drdianahoppe.com/wp-content/uploads/2017/04/image00-6.png', author: 'Darren Hardy, The Compound Effect', quote: 'Forget about willpower. It\'s time for why-power. Your choices are only meaningful when you connect them to your desires and dreams. The wisest and most motivating choices are the ones aligned with that which you identify as your purpose, your core self, and your highest values. You\'ve got to want something, and know why you want it, or you\'ll end up giving up too easily.'},
  {photoUrl: 'https://schools.au.reachout.com/-/media/schools/images/snapshot/pressure-to-do-well-at-school.png', author: 'Darren Hardy, The Compound Effect', quote: 'Seek out positive people who have achieved the success you want to create in your own life. Remember the adage: \“Never ask advice of someone with whom you wouldn\’t want to trade places.\"'},
  {photoUrl: 'https://thumbs.dreamstime.com/b/vector-illustration-sleepwalking-kid-sleepwalking-kid-100634952.jpg', author: 'Darren Hardy, The Compound Effect', quote: 'Your biggest challenge isn\’t that you\’ve intentionally been making bad choices. Heck, that would be easy to fix. Your biggest challenge is that you\’ve been sleepwalking through your choices.'},
  {photoUrl: 'https://thumbs.dreamstime.com/b/gap-analysis-measuring-resources-strategy-to-reach-target-comparison-current-state-challenge-obstacle-overcome-success-261035253.jpg', author: 'Darren Hardy, The Compound Effect', quote: 'The ultimate measure of a man is not where he stands in moments of comfort and convenience, but where he stands at times of challenge.'},
  {photoUrl: 'https://thumbs.dreamstime.com/b/united-people-25563244.jpg', author: 'Darren Hardy, The Compound Effect', quote: 'There\’s nothing wrong with ordinary. I just prefer to shoot for extraordinary.'},
  {photoUrl: 'https://tickthoseboxes.com.au/wp-content/uploads/elementor/thumbs/Accountable-pd3a61i81lwynnfob1pp0t1b2ujmefdh94yrtk021w.jpg', author: 'Darren Hardy, The Compound Effect', quote: 'No matter what has happened to you, take complete responsibility for it—good or bad, victory or defeat. Own it. My mentor Jim Rohn said, “The day you graduate from childhood to adulthood is the day you take full responsibility for your life.'},
  {photoUrl: 'https://www.jobstreet.com.ph/career-resources/wp-content/uploads/sites/3/2022/04/You-Can-Successfully-Manage-Your-Work-Life-With-Your-PassionsHeres-How.jpg', author: 'Cal newport, So Good They Can\'t Ignore You', quote: 'Passion comes after you put in the hard work to become excellent at something valuable, not before. In other words, what you do for a living is much less important than how you do it.'},
  {photoUrl: 'https://ijeoma.com.ng/wp-content/uploads/2019/05/OldWay.NewWayPhoto.jpeg', author: 'Cal Newport, So Good They Can\'t Ignore You', quote: 'If you want to love what you do, abandon the passion mindset (“what can the world offer me?”) and instead adopt the craftsman mindset (“what can I offer the world?”).'},
  {photoUrl: 'https://capital-placement.b-cdn.net/wp-content/uploads/2020/12/career-development.png', author: 'Cal Newport, So Good They Can\'t Ignore You', quote: 'No one owes you a great career, it argues; you need to earn it—and the process won\’t be easy.'},
  {photoUrl: 'https://media.istockphoto.com/id/666069948/photo/unpleased-skeptical-young-curly-brown-hair-woman.jpg?s=612x612&w=0&k=20&c=OMd8JAU64Hu8V9bsuw18ePkU9q38FKx842Z8jiPxlDM=', author: 'Cal Newport, So Good They Can\'t Ignore You', quote: 'If you/’re not uncomfortable, then you/’re probably stuck at an “acceptable level.'},
  {photoUrl: '', author: 'Cal Newport, So Good They Can\'t Ignore You', quote: 'The good news about deliberate practice is that it will push you past this plateau and into a realm where you have little competition.'},
  {photoUrl: '', author: 'Cal Newport, So Good They Can\'t Ignore You', quote: 'If your goal is to love what you do, you must first build up “career capital” by mastering rare and valuable skills, and then cash in this capital for the traits that define great work.'},
  {photoUrl: '', author: 'Cal Newport, So Good They Can\'t Ignore You', quote: 'Don\’t follow your passion; rather, let it follow you in your quest to become, in the words of my favorite Steve Martin quote, “so good that they can\’t ignore you.'},
  {photoUrl: '', author: 'Cal Newport, So Good They Can\'t Ignore You', quote: 'Doing things we know how to do well is enjoyable, and that\’s exactly the opposite of what deliberate practice demands…. Deliberate practice is above all an effort of focus and concentration. That is what makes it “deliberate,” as distinct from the mindless playing of scales or hitting of tennis balls that most people engage in.'},
  {photoUrl: '', author: 'Cal Newport, So Good They Can\'t Ignore You', quote: 'continuous and harsh feedback he received accelerated the growth of his ability.'},
  {photoUrl: '', author: 'Richard Dawkins, The Selfish Gene', quote: 'Any altruistic system is inherently unstable, because it is open to abuse by selfish individuals, ready to exploit it.'},
  {photoUrl: '', author: 'Susan Forward , Toxic Parents', quote: 'Denial is the lid on our emotional pressure cooker: the longer we leave it on, the more pressure we build up. Sooner or later, that pressure is bound to pop the lid, and we have an emotional crisis.'},
  {photoUrl: '', author: 'T. Harv Eker, Secrets of the Millionaire Mind', quote: 'What you focus on expands.'},
  {photoUrl: '', author: 'T. Harv Eker, Secrets of the Millionaire Mind', quote: 'It\’s not enough to be in the right place at the right time. You have to be the right person in the right place at the right time.'},
  {photoUrl: '', author: 'T. Harv Eker, Secrets of the Millionaire Mind', quote: 'The first element of change is awareness. You can\’t change something unless you know it exists.'},
  {photoUrl: '', author: 'T. Harv Eker, Secrets of the Millionaire Mind', quote: 'It\’s what\’s invisible that creates what\’s visible.'},
  {photoUrl: '', author: 'T. Harv Eker, Secrets of the Millionaire Mind', quote: 'If you want to fly with the eagles, don\’t swim with the ducks!'},
  {photoUrl: '', author: 'T. Harv Eker, Secrets of the Millionaire Mind', quote: 'When the subconscious mind must choose between deeply rooted emotions and logic, emotions will almost always win.'},
  {photoUrl: '', author: 'T. Harv Eker, Secrets of the Millionaire Mind', quote: 'The size of the problem is never the issue—what matters is the size of you!'},
  {photoUrl: '', author: 'T. Harv Eker, Secrets of the Millionaire Mind: Mastering the Inner Game of Wealth', quote: 'Wealth File 1. Rich people believe \"I create my life.\" Poor people believe \"Life happens to me.\" 2. Rich people play the money game to win. Poor people play the money game to not lose. 3. Rich people are committed to being rich. Poor people want to be rich. 4. Rich people think big. Poor people think small. 5. Rich people focus on opportunities. Poor people focus on obstacles. 6. Rich people admire other rich and successful people. Poor people resent rich and successful people. 7. Rich people associate with positive, successful people. Poor people associate with negative or unsuccessful people. 8. Rich people are willing to promote themselves and their value. Poor people think negatively about selling and promotion. 9. Rich people are bigger than their problems. Poor people are smaller than their problems. 10. Rich people are excellent receivers. Poor people are poor receivers. 11. Rich people choose to get paid based on results. Poor people choose to get paid based on time. 12. Rich people think \"both\". Poor people think \"either\/or\". 13. Rich people focus on their net worth. Poor people focus on their working income. 14. Rich people manage their money well. Poor people mismanage their money well. 15. Rich people have their money work hard for them. Poor people work hard for their money. 16. Rich people act in spite of fear. Poor people let fear stop them. 17. Rich people constantly learn and grow. Poor people think they already know.'},
  {photoUrl: '', author: '', quote: 'When arguing with a fool make sure he isn\'t doing the same thing.'},
  {photoUrl: '', author: 'Mark Twain', quote: 'Do not argue with a fool. He will drag you down to his level and beat you with experience.'},
  {photoUrl: '', author: 'Rumi', quote: 'The art of knowing is knowing what to ignore.'},
  {photoUrl: '', author: 'Jim Rohn', quote: 'Motivation is what gets you started. Habit is what keeps you going.'},
  {photoUrl: '', author: 'Tim Ferriss', quote: 'If you can\'t define it or act upon it, forget it.'},
  {photoUrl: '', author: 'Tim Ferriss', quote: 'What you do is infinitely more important than how you do it. Efficiency is still important, but it is useless unless applied to the right things.'},
  {photoUrl: '', author: 'Tim Ferriss', quote: 'Here are two truisms to keep in mind: 1. Doing something unimportant well does not make it important. 2. Requiring a lot of time does not make a task important.'},
  {photoUrl: '', author: '', quote: 'Hofstadter\'s Law: It always takes longer than you expect, even when you take into account Hofstadter\'s Law.'},
  {photoUrl: '', author: 'Mahatma Gandhi', quote: 'Action expresses priorities.'},
  {photoUrl: '', author: 'William James', quote: 'When you have to make a choice and don\'t make it, that is in itself a choice.'},
  {photoUrl: '', author: 'Jonathan Kozol', quote: 'Pick battles big enough to matter, small enough to win.'},
  {photoUrl: '', author: 'Kahlil Gibran', quote: 'I have learnt silence from the talkative, toleration from the intolerant, and kindness from the unkind; yet strange, I am ungrateful to these teachers.'},
  {photoUrl: '', author: '', quote: 'Always try to stop talking before people stop listening.'},
  {photoUrl: '', author: 'Woodrow Wilson', quote: 'It is better to remain silent and be thought a fool than to speak and remove all doubt Never murder a man when he\'s busy committing suicide.'},
  {photoUrl: '', author: '', quote: 'If you do not change direction, you may end up where you are heading'},
  {photoUrl: '', author: 'Mae West', quote: 'When choosing between two evils I always like to take the one I\`ve never tried before.'},
  {photoUrl: '', author: 'Robert Anthony', quote: 'Waiting is a trap. There will always be reasons to wait \– The truth is, there are only two things in life, reasons and results, and reasons simply don\’t count.'},
  {photoUrl: '', author: 'Ralph Waldo Emerson', quote: 'People only see what they are prepared to see.'},
  {photoUrl: '', author: 'Baltasar Gracian', quote: 'A wise man gets more use from his enemies than a fool from his friends.'},
  {photoUrl: '', author: 'Aristotle', quote: 'We are what we repeatedly do; excellence, then, is not an act but a habit.'},
  {photoUrl: '', author: 'Jim Morris', quote: 'I\'d like to fly. Then I wouldn\'t have to wait in airport security lines.'},
  {photoUrl: '', author: 'Robert Kiyosaki', quote: 'If you want to go somewhere, it is best to find someone who has already been there.'},
  {photoUrl: '', author: 'Gary Vaynerchuk', quote: 'How bad do you want it?'},
  {photoUrl: '', author: 'Gary Vaynerchuk', quote: 'There\’s no reason to do shit you hate. None.'},
  {photoUrl: '', author: ' Gary Vaynerchuk', quote: 'Never be romantic about how you make your money.'},
  {photoUrl: '', author: '', quote: 'The best way to expand your limits is to go to the edge of your limits'},
  {photoUrl: '', author: 'Abraham Maslow', quote: 'No great deed, private or public, has ever been undertaken in a bliss of certainty.'},
  {photoUrl: '', author: 'Dale Carnegie', quote: 'An old man was asked what had robbed him of joy in his life. His reply was, \“Things that never happened.\”'},
  {photoUrl: '', author: ' Napoleon Hill', quote: 'Action is the real measure of intelligence.'},
  {photoUrl: '', author: '', quote: 'The courage is not the ability to keep going, but going there where you have no courage'},
  {photoUrl: '', author: 'Larry Winget', quote: 'Excuses, Excuses, Excuses. The list of reasons for not doing very well in your life is actually a very short list. It should contain only your name.'},
  {photoUrl: '', author: 'Michael Jordan', quote: 'If you run into a wall, don\'t turn around and give up. Figure out how to climb it, go through it, or work around it.'},
  {photoUrl: '', author: 'Mark Twain', quote: 'Whenever you find yourself on the side of the majority, it\'s time to pause and reflect.'},
  {photoUrl: '', author: 'Fortune cookie', quote: 'Many a false step was made by standing still.'},
  {photoUrl: '', author: 'Benjamin Disraeli', quote: 'Action may not always bring happiness, but there is no happiness without action.'},
  {photoUrl: '', author: 'Albert Einstein', quote: 'Strive not to be a success, but rather to be of value.'},
  {photoUrl: '', author: 'Proverb', quote: 'If and When were planted, and Nothing grew.'},
  {photoUrl: '', author: 'George H. Lorimer', quote: 'Putting off an easy thing makes it hard, and putting off a hard one makes it impossible.'},
  {photoUrl: '', author: 'Dale Carnegie', quote: 'Do the hard jobs first. The easy jobs will take care of themselves.'},
  {photoUrl: '', author: '', quote: 'Procrastination is the grave in which opportunity is buried.'},
  {photoUrl: '', author: 'Robin Sharma', quote: 'To double your income, triple your investment in self-development.'},
  {photoUrl: '', author: 'Manoj Arora', quote: 'Coming out of your comfort zone is tough in the beginning, chaotic in the middle, and awesome in the end…because in the end, it shows you a whole new world.'},
  {photoUrl: '', author: 'Abraham Maslow', quote: 'One can choose to go back toward safety or forward toward growth. Growth must be chosen again and again; fear must be overcome again and again.'},
  {photoUrl: '', author: 'Chinese Proverb', quote: 'Your success is determined by how comfortable you feel outside your comfort zone. Man who waits for roast duck to fly into mouth must wait very, very long time.'},
  {photoUrl: '', author: 'Will Smith', quote: 'Stop letting people who do so little for you control so much of your mind, feelings & emotions.'},
  {photoUrl: '', author: 'Henry Ford', quote: 'Nothing is particularly hard if you divide it into small jobs.'},
  {photoUrl: '', author: '', quote: 'People would say bad things about you, because it is the only way their insignificant self can feel better than you'},
  {photoUrl: '', author: '', quote: 'Holding onto anger is like drinking poison and expecting the other person to die'},
  {photoUrl: '', author: 'Harvey Mackay', quote: 'You don\'t have to know everything, as long as you know people who know the things you don\'t.'},
  {photoUrl: '', author: 'George Santayana', quote: 'Those who cannot remember the past are condemned to repeat it.'},
  {photoUrl: '', author: 'Dagobert D. Runes', quote: 'Work is man\'s most natural form of relaxation.'},
  {photoUrl: '', author: '', quote: 'Employ your time in improving yourself by other men\'s writings, so that you shall gain easily what others have labored hard for.'},
  {photoUrl: '', author: 'Elon Musk', quote: 'I think that\'s the single best piece of advice: constantly think about how you could be doing things better and questioning yourself.'},
  {photoUrl: '', author: '', quote: 'It takes two to lie. One to lie and one to listen'},
  {photoUrl: '', author: 'Thomas J. Watson', quote: 'Would you like me to give you a formula for success? It\’s quite simple, really. Double your rate of failure.'},
  {photoUrl: '', author: 'Steve Jobs', quote: 'Remembering that you are going to die is the best way I know to avoid the trap of thinking you have something to lose.'},
  {photoUrl: '', author: 'Chinese proverb', quote: 'He who asks is a fool for five minutes, but he who does not ask remains a fool forever.'},
  {photoUrl: '', author: 'Bernard Shaw', quote: 'Those who cannot change their minds cannot change anything.'},
  {photoUrl: '', author: 'Walter Lippmann', quote: 'It requires wisdom to understand wisdom; the music is nothing if the audience is deaf.'},
  {photoUrl: '', author: 'Charles de Gaulle', quote: 'Always choose the hard way. On it you will not meet the competition.'},
  {photoUrl: '', author: 'OSHO', quote: 'The less people know, the more stubbornly they know it.'},
  {photoUrl: '', author: 'Christopher Morley', quote: 'There is only one success: to be able to spend your life in your own way.'},
  {photoUrl: '', author: 'Albert Einstein', quote: 'Insanity is doing the same thing over and over again and expecting different results.'},
  {photoUrl: '', author: 'Larry Winget', quote: 'Nobody ever wrote down a plan to be broke, fat, lazy, or stupid. Those things are what happen when you don\’t have a plan.'},
  {photoUrl: '', author: 'Milton Glaser', quote: 'There are three responses to a piece of design \– yes, no, and WOW! Wow is the one to aim for.'},
  {photoUrl: '', author: '', quote: 'The significant problems we have cannot be solved at the same level of thinking with which we created them.'},
  {photoUrl: '', author: 'David Allen', quote: 'If you don\’t pay appropriate attention to what has your attention, it will take more of your attention than it deserves.'},
  {photoUrl: '', author: 'Dr T.P.Chia', quote: 'Hard work does not necessarily guarantee success, but no success is possible without hard work.'},
  {photoUrl: '', author: 'Abraham Lincoln', quote: 'You don\'t help people by doing for them what they can do themselves.'},
  {photoUrl: '', author: 'Chinese proverb', quote: 'When the wind of change blows, some people build walls and other build windmills.'},
  {photoUrl: '', author: 'Peter Drucker', quote: 'Plans are only good intentions unless they immediately degenerate into hard work'},
  {photoUrl: '', author: 'Bernard M. Baruch', quote: 'Be who you are and say what you feel, because those who mind don\'t matter, and those who matter don\'t mind.'},
  {photoUrl: '', author: 'Dr T.P.Chia', quote: 'Don\’t give advice to fools. Don\’t argue with ignorant people. Don\’t associate with hypocrites.'},
  {photoUrl: '', author: 'Tom DeMarco', quote: 'You can\'t control what you can\'t measure.'},
  {photoUrl: '', author: 'Groucho Marx', quote: 'Learn from the mistakes of others. You can never live long enough to make them all yourself.'},
  {photoUrl: '', author: 'Stephen King', quote: 'The scariest moment is always just before you start.'},
  {photoUrl: '', author: 'Erza Scarlet', quote: 'If you truly desire greatness, you must first know what makes you weak.'},
  {photoUrl: '', author: 'Mark Twain', quote: 'Keep away from people who try to belittle your ambitions. Small people always do that, but the really great make you feel that you, too, can become great.'},
  {photoUrl: '', author: 'Robert Tew', quote: 'Respect yourself enough to walk away from anything that no longer serves you, grows you, or makes you happy.'},
  {photoUrl: '', author: 'Seth Godin', quote: 'Successful people are the ones who are breaking the rules.'},
  {photoUrl: '', author: 'Will Smith', quote: 'Being realistic is the most commonly traveled road to mediocrity.'},
  {photoUrl: '', author: 'Chris Colfer', quote: 'But one of the big lessons I have learned from my journey is you can\’t please everyone, so don\’t try...'},
  {photoUrl: '', author: 'Jeffrey Archer', quote: 'Better to lose with a wise man than win with a fool.'},
  {photoUrl: '', author: 'Vyacheslav Ulianitskiy', quote: 'If there\'s a dog barking at me I don\'t have to stand in all fours and bark in response.'},
  {photoUrl: '', author: 'Chinese Proverb', quote: 'The best time to plant a tree is twenty years ago. The second best time is now.'},
  {photoUrl: '', author: 'Elbert Hubbard', quote: 'To avoid criticism, do nothing, say nothing and be nothing.'},
  {photoUrl: '', author: 'J. Knyszewski', quote: 'Never ever do yourself what you can get others to do for you, faster, better and cheaper.'},
  {photoUrl: '', author: 'R. Brault', quote: 'Optimist: Someone who figures that taking a step backward after taking a step forward is not a disaster, it\'s a cha-cha…'},
  {photoUrl: '', author: 'Wayne Gretzky', quote: 'You miss 100 percent of the shots you don\’t take.'},
  {photoUrl: '', author: 'Leo Aikman', quote: 'You can tell more about a person by what they say about others than you can by what others say about them.'},
  {photoUrl: '', author: 'Aristotle', quote: 'It is the mark of an educated man to be able to entertain a thought without accepting it.'},
  {photoUrl: '', author: 'Henry Ford', quote: 'Whoever does what he already can, always remains what he already is.'},
  {photoUrl: '', author: 'Elbert Hubbard', quote: 'The world is moving so fast that the person who says it can\’t be done is generally interrupted by the person who is already doing it.'},
  {photoUrl: '', author: 'Robert Baden-Powel', quote: 'Look wide, and even when you think you are looking wide \– look wider still.'},
  {photoUrl: '', author: 'W. Churchill', quote: 'A joke is a very serious thing.'},
  {photoUrl: '', author: 'Winston Churchill', quote: 'Never laugh at the stupidity of others. It\'s your chance.'},
  {photoUrl: '', author: 'Henry Ford', quote: 'Thinking is the hardest work there is, which is probably the reason why so few engage in it.'},
  {photoUrl: '', author: 'S.L.Alder', quote: 'Your perspective on life comes from the cage you were held captive in.'},
  {photoUrl: '', author: 'C.G. Jung', quote: 'Everything that irritates us about others can lead us to an understanding of ourselves.'},
  {photoUrl: '', author: '', quote: 'Any time things appear to be going better, you have overlooked something'},
  {photoUrl: '', author: 'Shannon L. Alder', quote: 'The most important thing in communication is hearing what isn\'t being said. The art of reading between the lines is a lifelong quest of the wise.'},
  {photoUrl: '', author: 'Eleanor Roosevelt', quote: 'You wouldn\'t worry so much about what others think of you if you realized how seldom they do.'},
  {photoUrl: '', author: '', quote: 'The past cannot be changed.The future is yet in your power'},
  {photoUrl: '', author: 'Will Rogers', quote: 'If you find yourself in a hole, the first thing to do is stop digging.'},
  {photoUrl: '', author: 'Hazel Lee', quote: 'I held a moment in my hand, brilliant as a star, fragile as a flower, a tiny sliver of one hour. I dripped it carelessly, Ah! I didn\'t know, I held opportunity.'},
  {photoUrl: '', author: 'Hugh Allen', quote: 'Jumping at several small opportunities may get us there more quickly than waiting for one big one to come along.'},
  {photoUrl: '', author: 'Abraham Lincoln', quote: 'Give me six hours to chop down a tree and I will spend the first four sharpening the axe.'},
  {photoUrl: '', author: 'Voltaire', quote: 'Judge a man by his questions rather than his answers.'},
  {photoUrl: '', author: 'Cato', quote: 'Wise men learn more from fools than fools from wise men.'},
  {photoUrl: '', author: '', quote: 'Studying is not about time. It\’s about effort'},
  {photoUrl: '', author: '', quote: 'When you think it\’s too late, the truth is, it\’s still early.'},
  {photoUrl: '', author: 'Azim Premji', quote: 'If people are not laughing at your goals, your goals are too small'},
  {photoUrl: '', author: 'Eleanor Roosevelt', quote: 'Do one thing every day that scares you.'},
  {photoUrl: '', author: 'Edward Phelps', quote: 'The man who makes no mistakes does not usually make anything.'},
  {photoUrl: '', author: '', quote: 'The dogs bark, but the caravan goes on.'},
  {photoUrl: '', author: '', quote: 'A problem only becomes a problem when you see it as a problem. A problem is an opportunity.'},
  {photoUrl: '', author: '', quote: 'A chain is only as strong  as its weakest link.'},
  {photoUrl: '', author: 'Rockefeller', quote: 'He who works the whole day has no time to earn money.'},
  {photoUrl: '', author: 'Leonardo da Vinci', quote: 'Fear arises sooner than anything else.'},
  {photoUrl: '', author: 'Confucius', quote: 'Respect yourself and others will respect you.'},
  {photoUrl: '', author: 'Francois Fenelon', quote: 'The more you say, the less people remember.'},
  {photoUrl: '', author: 'Thomas Moore', quote: 'If you want to be successful you must look successful.'},
  {photoUrl: '', author: 'Lord Chesterfield', quote: 'Be wiser than other people, if you can, but do not tell them so.'},
  {photoUrl: '', author: 'Tony Robbins', quote: 'Success is doing what you want to do, when you want, where you want, with whom you want, as much as you want.'},
  {photoUrl: '', author: 'Roger H. Lincoln', quote: 'There are two rules for success. 1) Never tell everything you know'},
  {photoUrl: '', author: '', quote: 'Everyone is fighting a battle you know nothing about.'},
  {photoUrl: '', author: '', quote: 'Don\'t argue with a fool. A person watching may not see the difference.'},
  {photoUrl: '', author: 'Cal Newport', quote: 'Be so good they can\'t ignore you'},
  {photoUrl: '', author: 'Muneeb Ali', quote: 'When I’m old, how much would I be willing to pay to travel back in time and relive the moment that I\’m experiencing right now?'},
  {photoUrl: '', author: 'Jack Canfield', quote: 'Everything you want is on the other side of fear.'},
  {photoUrl: '', author: 'Adam Fisher', quote: 'Ignore the concept of \‘being yourself\’. Of course this is literally true by definition, but it is a way to avoid self-improvement.'},
  {photoUrl: '', author: 'Stephen Covey', quote: 'The main thing is to keep the main thing the main thing.'},
  {photoUrl: '', author: 'Strauss Zelnick', quote: 'Always ask what am I missing? And listen to the answer.'},
  {photoUrl: '', author: 'Christopher Carmichael', quote: 'You\'re 99 years old and on your death bed. If you had a chance to come back to right now, what would you do?'},
  {photoUrl: '', author: 'Jordan Peterson', quote: 'You can only find out what you actually believe (rather than what you think you believe) by watching how you act. You simply don\’t know what you believe, before that. You are too complex to understand yourself.'},
  {photoUrl: '', author: '', quote: 'Wisdom is knowing what you don\'t know'},
  {photoUrl: '', author: '', quote: 'Prepare for the best, be ready for the worst.'},
  {photoUrl: '', author: 'Rumi', quote: 'As you start to walk on the way, the way appears.'},
  {photoUrl: '', author: '', quote: 'Everything is art. The question is, are you conscious enough to see it?'},
  {photoUrl: '', author: 'Rumi', quote: 'What you seek is seeking you'},
  {photoUrl: '', author: 'Lin Yutang', quote: 'The wisdom of life consists in the elimination of non-essentials.'},
  {photoUrl: '', author: '', quote: 'You don\’t control what happens to you, but you can always control how you respond to it'},
  {photoUrl: '', author: 'Peter McWlliams and John-Roger', quote: 'A primary reason people don\’t do new things is because they want to do them perfectly \– first time. It\’s completely irrational, impractical, not workable and yet, it\’s how most people run their lives. It\’s called The Perfection Syndrome.'},
  {photoUrl: '', author: '', quote: 'The quality of your life is determined by the quality of the questions you ask'},
  {photoUrl: '', author: 'Theodore Roosevelt', quote: 'In a moment of decision, the best thing you can do is the right thing to do, the next best thing is the wrong thing, and the worst thing you can do is nothing.'},
  {photoUrl: '', author: 'Jim Rohn', quote: 'We must all suffer one of two things: the pain of discipline or the pain of regret or disappointment.'},
  {photoUrl: '', author: 'Tim Ferriss', quote: 'The person who has more options has more power. Don\'t wait until you need options to search for them. Take a sneak peek at the future now and it will make both action and being assertive easier.'},
  {photoUrl: '', author: 'Chinese proverb', quote: 'If you must play, decide on three things at the start: the rules of the game, the stakes, and the quitting time.'},
  {photoUrl: '', author: 'George Bernard Shaw', quote: 'Liberty means responsibility. That is why most men dread it.'},
  {photoUrl: '', author: 'Tim Ferriss', quote: 'Profit is only profitable to the extent that you can use it. For that you need time.'},
  {photoUrl: '', author: 'Tim Ferriss', quote: 'Doing the important and ignoring the trivial is hard because so much of the world seems to conspire to force crap upon you.'},
  {photoUrl: '', author: 'DAN GABLE', quote: 'The best defense is a good offense.'},
  {photoUrl: '', author: 'William of Occam', quote: 'It is vain to do with more what can be done with less.'},
  {photoUrl: '', author: '', quote: 'Being busy is most often used as a guise for avoiding the few critically important but uncomfortable actions'},
  {photoUrl: '', author: 'Albert Einstein', quote: 'Seek Experience, Not Information!  \“Information is not knowledge. The only source of knowledge is experience.\” You can learn about certain subject all you want, but you will never truly grasp it until you put your knowledge to practice and turn it into your personal experience.'},
  {photoUrl: '', author: 'Confucius', quote: 'I hear and I forget. I see and I remember. I do and I understand.'},
  {photoUrl: '', author: '', quote: 'The phrase \“This happened and it is bad\” is actually two impressions. The first — \“This happened\” — is objective. The second — \“it is bad\” — is subjective.'},
  {photoUrl: '', author: 'Benjamin Franklin', quote: 'Never ruin an apology with an excuse.'},
  {photoUrl: '', author: 'Cher', quote: 'Until you\'re ready to look foolish, you\'ll never have the possibility of being great.'},
  {photoUrl: '', author: 'Timothy Ferriss', quote: 'The fishing is best where the fewest go, and the collective insecurity of the world makes it easy for people to hit home runs while everyone else is aiming for base hits. There is just less competition for bigger goals. If you are insecure, guess what? The rest of the world is, too.'},
  {photoUrl: '', author: 'Gary Vaynerchuk', quote: 'No matter what you do, your job is to tell your story.'},
  {photoUrl: '', author: 'Johann Wolfgang von Goethe', quote: 'I respect the man who knows distinctly what he wishes. The greater part of all mischief in the world arises from the fact that men do not sufficiently understand their own aims. They have undertaken to build a tower, and spend no more labor on the foundation than would be necessary to erect a hut.'},
  {photoUrl: '', author: 'Walt Whitman', quote: 'Keep your face always toward the sunshine \– and shadows will fall behind you.'},
  {photoUrl: '', author: 'Jim Rohn', quote: 'Your level of success will rarely exceed your level of personal development because success is something you attract by the person you become.'},
  {photoUrl: '', author: 'Henry David Thoreau', quote: 'The question is not what you look at, but what you see.'},
  {photoUrl: '', author: 'Henry Ford', quote: 'Obstacles are those frightful things you see when you take your eyes off your goal.'},
  {photoUrl: '', author: 'Henry Ford', quote: 'It has been my observation that most people get ahead during the time that others waste.'},
  {photoUrl: '', author: '', quote: 'Perspective is everything'},
  {photoUrl: '', author: '', quote: 'As long as the answer is right, who cares if the question is wrong?'},
  {photoUrl: '', author: 'Wayne Gretzky', quote: 'I skate to where the puck is going to be, not where it has been.'},
  {photoUrl: '', author: 'Gordon R. Dickson', quote: 'Some people like my advice so much that they frame it upon the wall instead of using it.'},
  {photoUrl: '', author: 'John Maxwel', quote: 'Discipline is a decision to do what I really do not want to do in order to achieve what you really want to achieve.'},
  {photoUrl: '', author: 'Richard Feynman', quote: 'The first principle is that you must not fool yourself \– and you are the easiest person to fool.'},
  {photoUrl: '', author: 'Richard Dawkins, The Selfish Gene', quote: 'The rabbit runs faster than the fox, because the rabbit is running for his life while the fox is only running for his dinner.'},
  {photoUrl: '', author: 'Susan Forward, Toxic Parents', quote: 'Successful adult relationships, whether between lovers or friends, require a significant degree of vulnerability, trust, and openness.'},
  {photoUrl: '', author: 'Niccolò Machiavelli, The Prince', quote: 'Everyone sees what you appear to be, few experience what you really are.'},
  {photoUrl: '', author: 'Niccolo Machiavelli, The Prince', quote: 'If an injury has to be done to a man it should be so severe that his vengeance need not be feared.'},
  {photoUrl: '', author: 'Niccolò Machiavelli, The Prince', quote: 'The lion cannot protect himself from traps, and the fox cannot defend himself from wolves. One must therefore be a fox to recognize traps, and a lion to frighten wolves.'},
  {photoUrl: '', author: 'Niccolò Machiavelli, The Prince', quote: 'The first method for estimating the intelligence of a ruler is to look at the men he has around him.'},
  {photoUrl: '', author: 'Machiavelli Niccolo, The Prince', quote: 'There is no other way to guard yourself against flattery than by making men understand that telling you the truth will not offend you.'},
  {photoUrl: '', author: 'Niccolo Machiavelli', quote: 'Never was anything great achieved without danger.'},
  {photoUrl: '', author: 'Niccolò Machiavelli, The Prince', quote: 'Never attempt to win by force what can be won by deception.'},
  {photoUrl: '', author: 'Niccolo Machiavelli', quote: 'All courses of action are risky, so prudence is not in avoiding danger (it\'s impossible), but calculating risk and acting decisively. Make mistakes of ambition and not mistakes of sloth. Develop the strength to do bold things, not the strength to suffer.'},
  {photoUrl: '', author: 'Niccolo Machiavelli', quote: 'Where the willingness is great, the difficulties cannot be great.'},
  {photoUrl: '', author: 'Machiavelli Niccolo, The Prince', quote: '…he who seeks to deceive will always find someone who will allow himself to be deceived.'},
  {photoUrl: '', author: 'Niccolo Machiavelli, The Prince', quote: 'A prudent man should always follow in the path trodden by great men and imitate those who are most excellent, so that if he does not attain to their greatness, at any rate he will get some tinge of it.'},
  {photoUrl: '', author: 'Ryan Holiday', quote: 'The obstacle is the way'},
  {photoUrl: '', author: 'Epictetus', quote: 'It is impossible to learn that which one thinks one already knows.'},
  {photoUrl: '', author: 'Scott Adams and Tim Ferriss', quote: '\“I\’m thinking of these ideas and they\’re flowing through my head, I\’m monitoring my body; I\’m not monitoring my mind. And when my body changes, I have something that other people are going to care about, too.\” \“This bodily reaction—an involuntary half-chuckle, a rush of adrenaline, a surge of endorphins, a sharp change of emotions, etc.—can act as a metal detector for good material. It takes practice, but it works.\”'},
  {photoUrl: '', author: 'Rabelais', quote: 'If you want to avoid seeing an idiot you should turn your mirror over.'},
  {photoUrl: '', author: 'Chinese Proverb', quote: 'Failing to plan is planning to fail.'},
  {photoUrl: '', author: '', quote: 'Learning = behavioral change'},
  {photoUrl: '', author: '', quote: 'You cannot have enough of what you don\'t really want.'},
  {photoUrl: '', author: 'D. L. Moody', quote: 'The best way to show that a stick is crooked is not to argue about it or to spend time denouncing it, but to lay a straight stick alongside it'},
  {photoUrl: '', author: 'Richard Koch', quote: 'The 80-20 Rule (aka Pareto Principle)'},
  {photoUrl: '', author: 'Paulo Coelho, The Alchemist', quote: 'It\'s the possibility of having a dream come true that makes life interesting.'},
  {photoUrl: '', author: 'Paulo Coelho, The Alchemist', quote: 'There is only one thing that makes a dream impossible to achieve: the fear of failure.'},
  {photoUrl: '', author: '', quote: 'Do the best you can with what you have where you are.'},
]

module.exports.quotes = quotes;