const quotes = [
  {author: 'Goethe J.W.', quote: 'Everything is hard before it is easy'},
  {author: 'Martin Eden (Jack London)', quote: 'When playing in an unfamiliar game, never do the first move'},
  {author: 'Jerzy Gregorek', quote: 'Easy choices, hard life. Hard choices, easy life'},
  {author: '', quote: 'Watch your thoughts - they become words. Watch your words - they become actions. Watch your actions - they become habits. Watch your habits - they become a character. Watch your character - it determines your destiny'},
  {author: '', quote: 'We attract what we focus on'},
  {author: 'Jamie Foxx', quote: 'What is on the other side of fear? Nothing.'},
  {author: 'Janusz Wisniewski', quote: 'It is better to be self-confident, mistaken than to doubt, being right'},
  {author: 'Lucius Annaeus Seneca', quote: 'Nicht für die schule sondern für das leben lernen wir'},
  {author: 'John Powell', quote: 'The only real mistake is the one from which we learn nothing'},
  {author: 'Guy Julius Caesar', quote: 'Problems make smart people act and  make dumb people depressed.'},
  {author: 'Seneca', quote: 'We suffer more often in imagination than in reality'},
  {author: 'Darren Hardy, The Compound Effect', quote: 'You will never change your life until you change something you do daily. The secret of your success is found in your daily routine.'},
  {author: 'Darren Hardy, The Compound Effect', quote: 'Don\’t wish it were easier; wish you were better.'},
  {author: 'Darren Hardy, The Compound Effect', quote: 'You alone are responsible for what you do, don\’t do, or how you respond to what\’s done to you.'},
  {author: 'Darren Hardy, The Compound Effect', quote: 'Small, Smart Choices + Consistency + Time = RADICAL DIFFERENCE'},
  {author: 'Darren Hardy, The Compound Effect', quote: 'Forget about willpower. It\'s time for why-power. Your choices are only meaningful when you connect them to your desires and dreams. The wisest and most motivating choices are the ones aligned with that which you identify as your purpose, your core self, and your highest values. You\'ve got to want something, and know why you want it, or you\'ll end up giving up too easily.'},
  {author: 'Darren Hardy, The Compound Effect', quote: 'Seek out positive people who have achieved the success you want to create in your own life. Remember the adage: \“Never ask advice of someone with whom you wouldn\’t want to trade places.\"'},
  {author: 'Darren Hardy, The Compound Effect', quote: 'Your biggest challenge isn\’t that you\’ve intentionally been making bad choices. Heck, that would be easy to fix. Your biggest challenge is that you\’ve been sleepwalking through your choices.'},
  {author: 'Darren Hardy, The Compound Effect', quote: 'The ultimate measure of a man is not where he stands in moments of comfort and convenience, but where he stands at times of challenge.'},
  {author: 'Darren Hardy, The Compound Effect', quote: 'There\’s nothing wrong with ordinary. I just prefer to shoot for extraordinary.'},
  {author: 'Darren Hardy, The Compound Effect', quote: 'No matter what has happened to you, take complete responsibility for it—good or bad, victory or defeat. Own it. My mentor Jim Rohn said, “The day you graduate from childhood to adulthood is the day you take full responsibility for your life.'},
  {author: 'Cal newport, So Good They Can\'t Ignore You', quote: 'Passion comes after you put in the hard work to become excellent at something valuable, not before. In other words, what you do for a living is much less important than how you do it.'},
  {author: 'Cal Newport, So Good They Can\'t Ignore You', quote: 'If you want to love what you do, abandon the passion mindset (“what can the world offer me?”) and instead adopt the craftsman mindset (“what can I offer the world?”).'},
  {author: 'Cal Newport, So Good They Can\'t Ignore You', quote: 'No one owes you a great career, it argues; you need to earn it—and the process won\’t be easy.'},
  {author: 'Cal Newport, So Good They Can\'t Ignore You', quote: 'If you/’re not uncomfortable, then you/’re probably stuck at an “acceptable level.'},
  {author: 'Cal Newport, So Good They Can\'t Ignore You', quote: 'The good news about deliberate practice is that it will push you past this plateau and into a realm where you have little competition.'},
  {author: 'Cal Newport, So Good They Can\'t Ignore You', quote: 'If your goal is to love what you do, you must first build up “career capital” by mastering rare and valuable skills, and then cash in this capital for the traits that define great work.'},
  {author: 'Cal Newport, So Good They Can\'t Ignore You', quote: 'Don\’t follow your passion; rather, let it follow you in your quest to become, in the words of my favorite Steve Martin quote, “so good that they can\’t ignore you.'},
  {author: 'Cal Newport, So Good They Can\'t Ignore You', quote: 'Doing things we know how to do well is enjoyable, and that\’s exactly the opposite of what deliberate practice demands…. Deliberate practice is above all an effort of focus and concentration. That is what makes it “deliberate,” as distinct from the mindless playing of scales or hitting of tennis balls that most people engage in.'},
  {author: 'Cal Newport, So Good They Can\'t Ignore You', quote: 'continuous and harsh feedback he received accelerated the growth of his ability.'},
  {author: 'Richard Dawkins, The Selfish Gene', quote: 'Any altruistic system is inherently unstable, because it is open to abuse by selfish individuals, ready to exploit it.'},
  {author: 'Susan Forward , Toxic Parents', quote: 'Denial is the lid on our emotional pressure cooker: the longer we leave it on, the more pressure we build up. Sooner or later, that pressure is bound to pop the lid, and we have an emotional crisis.'},
  {author: 'T. Harv Eker, Secrets of the Millionaire Mind', quote: 'What you focus on expands.'},
  {author: 'T. Harv Eker, Secrets of the Millionaire Mind', quote: 'It\’s not enough to be in the right place at the right time. You have to be the right person in the right place at the right time.'},
  {author: 'T. Harv Eker, Secrets of the Millionaire Mind', quote: 'The first element of change is awareness. You can\’t change something unless you know it exists.'},
  {author: 'T. Harv Eker, Secrets of the Millionaire Mind', quote: 'It\’s what\’s invisible that creates what\’s visible.'},
  {author: 'T. Harv Eker, Secrets of the Millionaire Mind', quote: 'If you want to fly with the eagles, don\’t swim with the ducks!'},
  {author: 'T. Harv Eker, Secrets of the Millionaire Mind', quote: 'When the subconscious mind must choose between deeply rooted emotions and logic, emotions will almost always win.'},
  {author: 'T. Harv Eker, Secrets of the Millionaire Mind', quote: 'The size of the problem is never the issue—what matters is the size of you!'},
  {author: 'T. Harv Eker, Secrets of the Millionaire Mind: Mastering the Inner Game of Wealth', quote: 'Wealth File 1. Rich people believe \"I create my life.\" Poor people believe \"Life happens to me.\" 2. Rich people play the money game to win. Poor people play the money game to not lose. 3. Rich people are committed to being rich. Poor people want to be rich. 4. Rich people think big. Poor people think small. 5. Rich people focus on opportunities. Poor people focus on obstacles. 6. Rich people admire other rich and successful people. Poor people resent rich and successful people. 7. Rich people associate with positive, successful people. Poor people associate with negative or unsuccessful people. 8. Rich people are willing to promote themselves and their value. Poor people think negatively about selling and promotion. 9. Rich people are bigger than their problems. Poor people are smaller than their problems. 10. Rich people are excellent receivers. Poor people are poor receivers. 11. Rich people choose to get paid based on results. Poor people choose to get paid based on time. 12. Rich people think \"both\". Poor people think \"either\/or\". 13. Rich people focus on their net worth. Poor people focus on their working income. 14. Rich people manage their money well. Poor people mismanage their money well. 15. Rich people have their money work hard for them. Poor people work hard for their money. 16. Rich people act in spite of fear. Poor people let fear stop them. 17. Rich people constantly learn and grow. Poor people think they already know.'},
  {author: '', quote: 'When arguing with a fool make sure he isn\'t doing the same thing.'},
  {author: 'Mark Twain', quote: 'Do not argue with a fool. He will drag you down to his level and beat you with experience.'},
  {author: 'Rumi', quote: 'The art of knowing is knowing what to ignore.'},
  {author: 'Jim Rohn', quote: 'Motivation is what gets you started. Habit is what keeps you going.'},
  {author: 'Tim Ferriss', quote: 'If you can\'t define it or act upon it, forget it.'},
  {author: 'Tim Ferriss', quote: 'What you do is infinitely more important than how you do it. Efficiency is still important, but it is useless unless applied to the right things.'},
  {author: 'Tim Ferriss', quote: 'Here are two truisms to keep in mind: 1. Doing something unimportant well does not make it important. 2. Requiring a lot of time does not make a task important.'},
  {author: '', quote: 'Hofstadter\'s Law: It always takes longer than you expect, even when you take into account Hofstadter\'s Law.'},
  {author: 'Mahatma Gandhi', quote: 'Action expresses priorities.'},
  {author: 'William James', quote: 'When you have to make a choice and don\'t make it, that is in itself a choice.'},
  {author: 'Jonathan Kozol', quote: 'Pick battles big enough to matter, small enough to win.'},
  {author: 'Kahlil Gibran', quote: 'I have learnt silence from the talkative, toleration from the intolerant, and kindness from the unkind; yet strange, I am ungrateful to these teachers.'},
  {author: '', quote: 'Always try to stop talking before people stop listening.'},
  {author: 'Woodrow Wilson', quote: 'It is better to remain silent and be thought a fool than to speak and remove all doubt Never murder a man when he\'s busy committing suicide.'},
  {author: '', quote: 'If you do not change direction, you may end up where you are heading'},
  {author: 'Mae West', quote: 'When choosing between two evils I always like to take the one I\`ve never tried before.'},
  {author: 'Robert Anthony', quote: 'Waiting is a trap. There will always be reasons to wait \– The truth is, there are only two things in life, reasons and results, and reasons simply don\’t count.'},
  {author: 'Ralph Waldo Emerson', quote: 'People only see what they are prepared to see.'},
  {author: 'Baltasar Gracian', quote: 'A wise man gets more use from his enemies than a fool from his friends.'},
  {author: 'Aristotle', quote: 'We are what we repeatedly do; excellence, then, is not an act but a habit.'},
  {author: 'Jim Morris', quote: 'I\'d like to fly. Then I wouldn\'t have to wait in airport security lines.'},
  {author: 'Robert Kiyosaki', quote: 'If you want to go somewhere, it is best to find someone who has already been there.'},
  {author: 'Gary Vaynerchuk', quote: 'How bad do you want it?'},
  {author: 'Gary Vaynerchuk', quote: 'There\’s no reason to do shit you hate. None.'},
  {author: ' Gary Vaynerchuk', quote: 'Never be romantic about how you make your money.'},
  {author: '', quote: 'The best way to expand your limits is to go to the edge of your limits'},
  {author: 'Abraham Maslow', quote: 'No great deed, private or public, has ever been undertaken in a bliss of certainty.'},
  {author: 'Dale Carnegie', quote: 'An old man was asked what had robbed him of joy in his life. His reply was, \“Things that never happened.\”'},
  {author: ' Napoleon Hill', quote: 'Action is the real measure of intelligence.'},
  {author: '', quote: 'The courage is not the ability to keep going, but going there where you have no courage'},
  {author: 'Larry Winget', quote: 'Excuses, Excuses, Excuses. The list of reasons for not doing very well in your life is actually a very short list. It should contain only your name.'},
  {author: 'Michael Jordan', quote: 'If you run into a wall, don\'t turn around and give up. Figure out how to climb it, go through it, or work around it.'},
  {author: 'Mark Twain', quote: 'Whenever you find yourself on the side of the majority, it\'s time to pause and reflect.'},
  {author: 'Fortune cookie', quote: 'Many a false step was made by standing still.'},
  {author: 'Benjamin Disraeli', quote: 'Action may not always bring happiness, but there is no happiness without action.'},
  {author: 'Albert Einstein', quote: 'Strive not to be a success, but rather to be of value.'},
  {author: 'Proverb', quote: 'If and When were planted, and Nothing grew.'},
  {author: 'George H. Lorimer', quote: 'Putting off an easy thing makes it hard, and putting off a hard one makes it impossible.'},
  {author: 'Dale Carnegie', quote: 'Do the hard jobs first. The easy jobs will take care of themselves.'},
  {author: '', quote: 'Procrastination is the grave in which opportunity is buried.'},
  {author: 'Robin Sharma', quote: 'To double your income, triple your investment in self-development.'},
  {author: 'Manoj Arora', quote: 'Coming out of your comfort zone is tough in the beginning, chaotic in the middle, and awesome in the end…because in the end, it shows you a whole new world.'},
  {author: 'Abraham Maslow', quote: 'One can choose to go back toward safety or forward toward growth. Growth must be chosen again and again; fear must be overcome again and again.'},
  {author: 'Chinese Proverb', quote: 'Your success is determined by how comfortable you feel outside your comfort zone. Man who waits for roast duck to fly into mouth must wait very, very long time.'},
  {author: 'Will Smith', quote: 'Stop letting people who do so little for you control so much of your mind, feelings & emotions.'},
  {author: 'Henry Ford', quote: 'Nothing is particularly hard if you divide it into small jobs.'},
  {author: '', quote: 'People would say bad things about you, because it is the only way their insignificant self can feel better than you'},
  {author: '', quote: 'Holding onto anger is like drinking poison and expecting the other person to die'},
  {author: 'Harvey Mackay', quote: 'You don\'t have to know everything, as long as you know people who know the things you don\'t.'},
  {author: 'George Santayana', quote: 'Those who cannot remember the past are condemned to repeat it.'},
  {author: 'Dagobert D. Runes', quote: 'Work is man\'s most natural form of relaxation.'},
  {author: '', quote: 'Employ your time in improving yourself by other men\'s writings, so that you shall gain easily what others have labored hard for.'},
  {author: 'Elon Musk', quote: 'I think that\'s the single best piece of advice: constantly think about how you could be doing things better and questioning yourself.'},
  {author: '', quote: 'It takes two to lie. One to lie and one to listen'},
  {author: 'Thomas J. Watson', quote: 'Would you like me to give you a formula for success? It\’s quite simple, really. Double your rate of failure.'},
  {author: 'Steve Jobs', quote: 'Remembering that you are going to die is the best way I know to avoid the trap of thinking you have something to lose.'},
  {author: 'Chinese proverb', quote: 'He who asks is a fool for five minutes, but he who does not ask remains a fool forever.'},
  {author: 'Bernard Shaw', quote: 'Those who cannot change their minds cannot change anything.'},
  {author: 'Walter Lippmann', quote: 'It requires wisdom to understand wisdom; the music is nothing if the audience is deaf.'},
  {author: 'Charles de Gaulle', quote: 'Always choose the hard way. On it you will not meet the competition.'},
  {author: 'OSHO', quote: 'The less people know, the more stubbornly they know it.'},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
  {author: '', quote: ''},
]

module.exports.quotes = quotes;